name: Workflow for Codecov
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
