name: workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - name: Test And CI
        run: npm run test
      - name: Upload coverage to Codecov
        # https://github.com/codecov/codecov-bash/blob/1044b7a243e0ea0c05ed43c2acd8b7bb7cef340c/codecov#L158
        run: npx codecov
          -f "./coverage/coverage-final.json"
          -y "./.codecov.yml"
          -b ${{ github.head_ref }}
          -c ${{ github.event.after }}
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

